version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: desafio_zoppy
    depends_on:
      - db
    volumes:
      - ./backend:/app         
      - /app/node_modules       
    command: sh -c "/wait-for-db.sh && npm run start:dev -- --watch --poll=1000"


  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: desafio_zoppy
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ./frontend:/app        
      - /app/node_modules      
    command: npm run start -- --host 0.0.0.0 --poll=2000
    depends_on:
      - backend

volumes:
  mysql-data:
