FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache inotify-tools


COPY package*.json ./
RUN npm install --legacy-peer-deps

# Espera o Mysql
COPY wait-for-db.sh /wait-for-db.sh
RUN chmod +x /wait-for-db.sh

# Porta do NestJS
EXPOSE 3000
CMD sh -c "/wait-for-db.sh && npm run start:dev -- --watch --poll=1000"
